CREATE TABLE REQUEST_MESSAGE(ID INT PRIMARY KEY AUTO_INCREMENT,
                  INCOMING_MESSAGE VARCHAR(7999),
                  TRANSLATED_MESSAGE VARCHAR(7999),
                  SOURCE_LANGUAGE VARCHAR(10),
                  TARGET_LANGUAGE VARCHAR(10),
                  REQUEST_TIME VARCHAR(50),
                  REQUEST_IP VARCHAR(50)
                 );

CREATE TABLE REQUEST_WORD(ID_REQUEST INT,
                INCOMING_WORD VARCHAR(255),
                TRANSLATED_WORD VARCHAR(255),
                FOREIGN KEY (ID_REQUEST) REFERENCES REQUEST_MESSAGE(ID),
                PRIMARY KEY (ID_REQUEST, INCOMING_WORD, TRANSLATED_WORD)
);